/* src/config_cbc.h.  Generated by configure.  */
/* src/config_cbc.h.in. */

/* Version number of project */
#define CBC_VERSION "2.7.5"

/* Major Version number of project */
#define CBC_VERSION_MAJOR 2

/* Minor Version number of project */
#define CBC_VERSION_MINOR 7

/* Release Version number of project */
#define CBC_VERSION_RELEASE 5
