/* src/config_coinutils.h.  Generated by configure.  */
/* inc/config_coinutils.h.in.  */

#ifndef __CONFIG_COINUTILS_H__
#define __CONFIG_COINUTILS_H__

/* Version number of project */
#define COINUTILS_VERSION "2.8.5"

/* Major Version number of project */
#define COINUTILS_VERSION_MAJOR 2

/* Minor Version number of project */
#define COINUTILS_VERSION_MINOR 8

/* Release Version number of project */
#define COINUTILS_VERSION_RELEASE 5

/* Define to 64bit integer type */
#define COIN_INT64_T long long

/* Define to integer type capturing pointer */
#define COIN_INTPTR_T long long

/* Define to 64bit unsigned integer type */
#define COIN_UINT64_T long long

#endif
