# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MP1H_R.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(112, 521)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(10, 150, 31, 16))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("button.png"))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(10, 160, 31, 16))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("button.png"))
        self.label_2.setObjectName("label_2")
        self.label_11 = QtWidgets.QLabel(Form)
        self.label_11.setGeometry(QtCore.QRect(20, 150, 55, 16))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(Form)
        self.label_12.setGeometry(QtCore.QRect(20, 160, 55, 16))
        self.label_12.setObjectName("label_12")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(10, 190, 31, 16))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("button.png"))
        self.label_3.setObjectName("label_3")
        self.label_13 = QtWidgets.QLabel(Form)
        self.label_13.setGeometry(QtCore.QRect(20, 200, 55, 16))
        self.label_13.setObjectName("label_13")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(10, 200, 31, 16))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("button.png"))
        self.label_4.setObjectName("label_4")
        self.label_14 = QtWidgets.QLabel(Form)
        self.label_14.setGeometry(QtCore.QRect(20, 190, 55, 16))
        self.label_14.setObjectName("label_14")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(10, 230, 31, 16))
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap("button.png"))
        self.label_5.setObjectName("label_5")
        self.label_15 = QtWidgets.QLabel(Form)
        self.label_15.setGeometry(QtCore.QRect(20, 240, 55, 16))
        self.label_15.setObjectName("label_15")
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(10, 240, 31, 16))
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap("button.png"))
        self.label_6.setObjectName("label_6")
        self.label_16 = QtWidgets.QLabel(Form)
        self.label_16.setGeometry(QtCore.QRect(20, 230, 55, 16))
        self.label_16.setObjectName("label_16")
        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setGeometry(QtCore.QRect(10, 270, 31, 16))
        self.label_7.setText("")
        self.label_7.setPixmap(QtGui.QPixmap("button.png"))
        self.label_7.setObjectName("label_7")
        self.label_17 = QtWidgets.QLabel(Form)
        self.label_17.setGeometry(QtCore.QRect(20, 280, 55, 16))
        self.label_17.setObjectName("label_17")
        self.label_8 = QtWidgets.QLabel(Form)
        self.label_8.setGeometry(QtCore.QRect(10, 280, 31, 16))
        self.label_8.setText("")
        self.label_8.setPixmap(QtGui.QPixmap("button.png"))
        self.label_8.setObjectName("label_8")
        self.label_18 = QtWidgets.QLabel(Form)
        self.label_18.setGeometry(QtCore.QRect(20, 270, 55, 16))
        self.label_18.setObjectName("label_18")
        self.label_9 = QtWidgets.QLabel(Form)
        self.label_9.setGeometry(QtCore.QRect(10, 310, 31, 16))
        self.label_9.setText("")
        self.label_9.setPixmap(QtGui.QPixmap("button.png"))
        self.label_9.setObjectName("label_9")
        self.label_19 = QtWidgets.QLabel(Form)
        self.label_19.setGeometry(QtCore.QRect(20, 320, 55, 16))
        self.label_19.setObjectName("label_19")
        self.label_10 = QtWidgets.QLabel(Form)
        self.label_10.setGeometry(QtCore.QRect(10, 320, 31, 16))
        self.label_10.setText("")
        self.label_10.setPixmap(QtGui.QPixmap("button.png"))
        self.label_10.setObjectName("label_10")
        self.label_20 = QtWidgets.QLabel(Form)
        self.label_20.setGeometry(QtCore.QRect(20, 310, 55, 16))
        self.label_20.setObjectName("label_20")
        self.label_61 = QtWidgets.QLabel(Form)
        self.label_61.setGeometry(QtCore.QRect(30, 360, 55, 16))
        self.label_61.setText("")
        self.label_61.setPixmap(QtGui.QPixmap("../../NetPlanner/MP2X_panel/CH.png"))
        self.label_61.setObjectName("label_61")
        self.label_21 = QtWidgets.QLabel(Form)
        self.label_21.setGeometry(QtCore.QRect(30, 420, 55, 16))
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(Form)
        self.label_22.setGeometry(QtCore.QRect(20, 410, 31, 16))
        self.label_22.setText("")
        self.label_22.setPixmap(QtGui.QPixmap("button.png"))
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(Form)
        self.label_23.setGeometry(QtCore.QRect(20, 420, 31, 16))
        self.label_23.setText("")
        self.label_23.setPixmap(QtGui.QPixmap("button.png"))
        self.label_23.setObjectName("label_23")
        self.label_24 = QtWidgets.QLabel(Form)
        self.label_24.setGeometry(QtCore.QRect(30, 410, 55, 16))
        self.label_24.setObjectName("label_24")
        self.label_25 = QtWidgets.QLabel(Form)
        self.label_25.setGeometry(QtCore.QRect(10, 360, 55, 16))
        self.label_25.setObjectName("label_25")
        self.label_26 = QtWidgets.QLabel(Form)
        self.label_26.setGeometry(QtCore.QRect(40, 70, 31, 16))
        self.label_26.setText("")
        self.label_26.setPixmap(QtGui.QPixmap("button.png"))
        self.label_26.setObjectName("label_26")
        self.label_27 = QtWidgets.QLabel(Form)
        self.label_27.setGeometry(QtCore.QRect(50, 60, 55, 16))
        self.label_27.setObjectName("label_27")
        self.label_28 = QtWidgets.QLabel(Form)
        self.label_28.setGeometry(QtCore.QRect(40, 60, 31, 16))
        self.label_28.setText("")
        self.label_28.setPixmap(QtGui.QPixmap("button.png"))
        self.label_28.setObjectName("label_28")
        self.label_29 = QtWidgets.QLabel(Form)
        self.label_29.setGeometry(QtCore.QRect(50, 70, 55, 16))
        self.label_29.setObjectName("label_29")
        self.label_30 = QtWidgets.QLabel(Form)
        self.label_30.setGeometry(QtCore.QRect(40, 80, 31, 16))
        self.label_30.setText("")
        self.label_30.setPixmap(QtGui.QPixmap("button.png"))
        self.label_30.setObjectName("label_30")
        self.label_31 = QtWidgets.QLabel(Form)
        self.label_31.setGeometry(QtCore.QRect(50, 80, 55, 16))
        self.label_31.setObjectName("label_31")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_11.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:6pt;\">ACT</span></p></body></html>"))
        self.label_12.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:6pt;\">SF</span></p></body></html>"))
        self.label_13.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:6pt;\">SF</span></p></body></html>"))
        self.label_14.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:6pt;\">ACT</span></p></body></html>"))
        self.label_15.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:6pt;\">SF</span></p></body></html>"))
        self.label_16.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:6pt;\">ACT</span></p></body></html>"))
        self.label_17.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:6pt;\">SF</span></p></body></html>"))
        self.label_18.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:6pt;\">ACT</span></p></body></html>"))
        self.label_19.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:6pt;\">SF</span></p></body></html>"))
        self.label_20.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:6pt;\">ACT</span></p></body></html>"))
        self.label_21.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:6pt;\">SF</span></p></body></html>"))
        self.label_24.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:6pt;\">ACT</span></p></body></html>"))
        self.label_25.setText(_translate("Form", "CH"))
        self.label_27.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:6pt;\">ACT</span></p></body></html>"))
        self.label_29.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:6pt;\">FAIL</span></p></body></html>"))
        self.label_31.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:6pt;\">W/P</span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
