from PySide2.QtWidgets import *
from PySide2.QtCore import *
from PySide2.QtGui import *
import sys
import os
from data import *


class MP1H_R_Demand(QWidget):
    def __init__(self, Panel_ID, nodename):
        super(MP1H_R_Demand, self).__init__()

        self.id = Panel_ID
        self.nodename = nodename
        self.setFixedSize(112, 521)

        self.label = QLabel(self)
        self.label.setGeometry(QRect(10, 150, 31, 16))
        self.label.setText("")
        self.label.setPixmap(QPixmap(os.path.join("MP1H_Demand","button.png")))
        self.label.setObjectName("label")
        self.label_2 = QLabel(self)
        self.label_2.setGeometry(QRect(10, 160, 31, 16))
        self.label_2.setText("")
        self.label_2.setPixmap(QPixmap(os.path.join("MP1H_Demand","button.png")))
        self.label_2.setObjectName("label_2")
        self.label_11 = QLabel(self)
        self.label_11.setGeometry(QRect(20, 150, 55, 16))
        self.label_11.setObjectName("label_11")
        self.label_12 = QLabel(self)
        self.label_12.setGeometry(QRect(20, 160, 55, 16))
        self.label_12.setObjectName("label_12")
        self.label_3 = QLabel(self)
        self.label_3.setGeometry(QRect(10, 190, 31, 16))
        self.label_3.setText("")
        self.label_3.setPixmap(QPixmap(os.path.join("MP1H_Demand","button.png")))
        self.label_3.setObjectName("label_3")
        self.label_13 = QLabel(self)
        self.label_13.setGeometry(QRect(20, 200, 55, 16))
        self.label_13.setObjectName("label_13")
        self.label_4 = QLabel(self)
        self.label_4.setGeometry(QRect(10, 200, 31, 16))
        self.label_4.setText("")
        self.label_4.setPixmap(QPixmap(os.path.join("MP1H_Demand","button.png")))
        self.label_4.setObjectName("label_4")
        self.label_14 = QLabel(self)
        self.label_14.setGeometry(QRect(20, 190, 55, 16))
        self.label_14.setObjectName("label_14")
        self.label_5 = QLabel(self)
        self.label_5.setGeometry(QRect(10, 230, 31, 16))
        self.label_5.setText("")
        self.label_5.setPixmap(QPixmap(os.path.join("MP1H_Demand","button.png")))
        self.label_5.setObjectName("label_5")
        self.label_15 = QLabel(self)
        self.label_15.setGeometry(QRect(20, 240, 55, 16))
        self.label_15.setObjectName("label_15")
        self.label_6 = QLabel(self)
        self.label_6.setGeometry(QRect(10, 240, 31, 16))
        self.label_6.setText("")
        self.label_6.setPixmap(QPixmap(os.path.join("MP1H_Demand","button.png")))
        self.label_6.setObjectName("label_6")
        self.label_16 = QLabel(self)
        self.label_16.setGeometry(QRect(20, 230, 55, 16))
        self.label_16.setObjectName("label_16")
        self.label_7 = QLabel(self)
        self.label_7.setGeometry(QRect(10, 270, 31, 16))
        self.label_7.setText("")
        self.label_7.setPixmap(QPixmap(os.path.join("MP1H_Demand","button.png")))
        self.label_7.setObjectName("label_7")
        self.label_17 = QLabel(self)
        self.label_17.setGeometry(QRect(20, 280, 55, 16))
        self.label_17.setObjectName("label_17")
        self.label_8 = QLabel(self)
        self.label_8.setGeometry(QRect(10, 280, 31, 16))
        self.label_8.setText("")
        self.label_8.setPixmap(QPixmap(os.path.join("MP1H_Demand","button.png")))
        self.label_8.setObjectName("label_8")
        self.label_18 = QLabel(self)
        self.label_18.setGeometry(QRect(20, 270, 55, 16))
        self.label_18.setObjectName("label_18")
        self.label_9 = QLabel(self)
        self.label_9.setGeometry(QRect(10, 310, 31, 16))
        self.label_9.setText("")
        self.label_9.setPixmap(QPixmap(os.path.join("MP1H_Demand","button.png")))
        self.label_9.setObjectName("label_9")
        self.label_19 = QLabel(self)
        self.label_19.setGeometry(QRect(20, 320, 55, 16))
        self.label_19.setObjectName("label_19")
        self.label_10 = QLabel(self)
        self.label_10.setGeometry(QRect(10, 320, 31, 16))
        self.label_10.setText("")
        self.label_10.setPixmap(QPixmap(os.path.join("MP1H_Demand","button.png")))
        self.label_10.setObjectName("label_10")
        self.label_20 = QLabel(self)
        self.label_20.setGeometry(QRect(20, 310, 55, 16))
        self.label_20.setObjectName("label_20")
        self.label_61 = QLabel(self)
        self.label_61.setGeometry(QRect(30, 360, 55, 16))
        self.label_61.setText("")
        self.label_61.setPixmap(QPixmap(os.path.join("MP1H_Demand","CH.png")))
        self.label_61.setObjectName("label_61")
        self.label_21 = QLabel(self)
        self.label_21.setGeometry(QRect(30, 420, 55, 16))
        self.label_21.setObjectName("label_21")
        self.label_22 = QLabel(self)
        self.label_22.setGeometry(QRect(20, 410, 31, 16))
        self.label_22.setText("")
        self.label_22.setPixmap(QPixmap(os.path.join("MP1H_Demand","button.png")))
        self.label_22.setObjectName("label_22")
        self.label_23 = QLabel(self)
        self.label_23.setGeometry(QRect(20, 420, 31, 16))
        self.label_23.setText("")
        self.label_23.setPixmap(QPixmap(os.path.join("MP1H_Demand","button.png")))
        self.label_23.setObjectName("label_23")
        self.label_24 = QLabel(self)
        self.label_24.setGeometry(QRect(30, 410, 55, 16))
        self.label_24.setObjectName("label_24")
        self.label_25 = QLabel(self)
        self.label_25.setGeometry(QRect(10, 360, 55, 16))
        self.label_25.setObjectName("label_25")
        self.label_26 = QLabel(self)
        self.label_26.setGeometry(QRect(40, 70, 31, 16))
        self.label_26.setText("")
        self.label_26.setPixmap(QPixmap(os.path.join("MP1H_Demand","button.png")))
        self.label_26.setObjectName("label_26")
        self.label_27 = QLabel(self)
        self.label_27.setGeometry(QRect(50, 60, 55, 16))
        self.label_27.setObjectName("label_27")
        self.label_28 = QLabel(self)
        self.label_28.setGeometry(QRect(40, 60, 31, 16))
        self.label_28.setText("")
        self.label_28.setPixmap(QPixmap(os.path.join("MP1H_Demand","button.png")))
        self.label_28.setObjectName("label_28")
        self.label_29 = QLabel(self)
        self.label_29.setGeometry(QRect(50, 70, 55, 16))
        self.label_29.setObjectName("label_29")
        self.label_30 = QLabel(self)
        self.label_30.setGeometry(QRect(40, 80, 31, 16))
        self.label_30.setText("")
        self.label_30.setPixmap(QPixmap(os.path.join("MP1H_Demand","button.png")))
        self.label_30.setObjectName("label_30")
        self.label_31 = QLabel(self)
        self.label_31.setGeometry(QRect(50, 80, 55, 16))
        self.label_31.setObjectName("label_31")

        self.retranslateUi()
        QMetaObject.connectSlotsByName(self)

    def retranslateUi(self):
        _translate = QCoreApplication.translate
        self.setWindowTitle(_translate("self", "self"))
        self.label_11.setText(_translate("self", "<html><head/><body><p><span style=\" font-size:6pt;\">ACT</span></p></body></html>"))
        self.label_12.setText(_translate("self", "<html><head/><body><p><span style=\" font-size:6pt;\">SF</span></p></body></html>"))
        self.label_13.setText(_translate("self", "<html><head/><body><p><span style=\" font-size:6pt;\">SF</span></p></body></html>"))
        self.label_14.setText(_translate("self", "<html><head/><body><p><span style=\" font-size:6pt;\">ACT</span></p></body></html>"))
        self.label_15.setText(_translate("self", "<html><head/><body><p><span style=\" font-size:6pt;\">SF</span></p></body></html>"))
        self.label_16.setText(_translate("self", "<html><head/><body><p><span style=\" font-size:6pt;\">ACT</span></p></body></html>"))
        self.label_17.setText(_translate("self", "<html><head/><body><p><span style=\" font-size:6pt;\">SF</span></p></body></html>"))
        self.label_18.setText(_translate("self", "<html><head/><body><p><span style=\" font-size:6pt;\">ACT</span></p></body></html>"))
        self.label_19.setText(_translate("self", "<html><head/><body><p><span style=\" font-size:6pt;\">SF</span></p></body></html>"))
        self.label_20.setText(_translate("self", "<html><head/><body><p><span style=\" font-size:6pt;\">ACT</span></p></body></html>"))
        self.label_21.setText(_translate("self", "<html><head/><body><p><span style=\" font-size:6pt;\">SF</span></p></body></html>"))
        self.label_24.setText(_translate("self", "<html><head/><body><p><span style=\" font-size:6pt;\">ACT</span></p></body></html>"))
        self.label_25.setText(_translate("self", "CH"))
        self.label_27.setText(_translate("self", "<html><head/><body><p><span style=\" font-size:6pt;\">ACT</span></p></body></html>"))
        self.label_29.setText(_translate("self", "<html><head/><body><p><span style=\" font-size:6pt;\">FAIL</span></p></body></html>"))
        self.label_31.setText(_translate("self", "<html><head/><body><p><span style=\" font-size:6pt;\">W/P</span></p></body></html>"))

